### PR TITLE
Feature: Support multi-language interface injection

### PR DESCRIPTION
**Pull request by Berny23**
- add config variable for Steam language
- get official Steam translation from js files
- fix settings page and interface tab injection for all languages
- remove editor optimization file from git

Working example with Steam set to German:
image

### CODE REVIEW

**Comment by ShadowMonster99** [comment]
problem fixed by checking tab by index and check settings window by queryselector

**Comment by ShadowMonster99** [comment]
Being that your a c++ developer and you know what your doing, would you be interested in helping maintain the project?

Even though these changes weren't made at the time, I am most likely going to now use a portion of them to implement something slightly different.

**Comment by ShadowMonster99** [comment]
Also thank you for contributing, I really appreciate it!

**Comment by ShadowMonster99** [comment]
Reopening and requesting changes. 
- Discard everything except the localization manager API in config.cpp
- Add auto detect Steam language, without the use of registry (linux cross-compatability)

Example
```c++
config.get_local_from_eng("Settings") -> returns Settings in current language
```

**Review by ShadowMonster99 — CHANGES_REQUESTED** [review]
[Change Request](https://github.com/ShadowMonster99/millennium-steam-patcher/pull/2#issuecomment-2024149842)

**Comment by Berny23** [comment]
Hi, I completely switched to Arch Linux in the meantime, so I stopped using this patcher. Now, I'm using this skin: https://github.com/tkashkin/Adwaita-for-Steam

Although, having linux support here would be pretty nice. I just don't really have the time for active development.

**Comment by ShadowMonster99** [comment]
No worries, Have a good one!

**Pull request closed without merging**
